version: "1.0"
info:
  model: int-scaffold
packages:
- name: Emea02user_Israel_SuperIPaaSProject
  gitServerName: michalit0
  gitUrl: https://github.com/michalit0/Emea02user_Israel_SuperIPaaSProject
  gitUsername: michalit0
  gitBranch: main
- name: Shipment
  gitServerName: michalit0
  gitUrl: https://github.com/michalit0
  gitUsername: michalit0
  gitBranch: master
services:
- serviceName: project.emea02user_israel_superipaas.integrations:ShipmentHandler
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.emea02user_israel_superipaas.integrations:CustomsHandler
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: project.emea02user_israel_superipaas.integrations:B64ShipmentHandler
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: pub.string:base64Decode
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.document:bytesToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.emea02user_israel_superipaas.integrations:ComplexDataHandler
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: project.emea02user_israel_superipaas.integrations:TEST_API_IMP
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: project.emea02user_israel_superipaas.integrations:ShipmentReduce
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: project.emea02user_israel_superipaas.integrations:CustomsReduce
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
- serviceName: project.emea02user_israel_superipaas.integrations:ShipmentConvert
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
  - name: Shipment
    version: "1.0"
- serviceName: ShipmentPackage.integrations:ShipmentDetails
  packages:
  - name: Shipment
    version: "1.0"
- serviceName: ShipmentPackage.integrations:ShipmentDetails1
  packages:
  - name: Shipment
    version: "1.0"
- serviceName: pub.flow:savePipelineToFile
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.emea02user_israel_superipaas.integrations:CustomConvert
  packages:
  - name: Emea02user_Israel_SuperIPaaSProject
    version: "1.0"
  - name: Shipment
    version: "1.0"
- serviceName: ShipmentPackage.integrations:CustomsDetails
  packages:
  - name: Shipment
    version: "1.0"
